---
title: "dv final project"
author: "Ruoyi Gao"
date: "4/30/2022"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(shiny)
library(ggplot2)
library(scales)
library(plotly)
```

```{r}
data <- read.csv("/Users/gabriellecici/R/covid_data.csv")
```

```{r}
data<-data %>% select(-X)
```

```{r}
country = unique(data["location"])
```

```{r}
data$date <- as.Date(data$date)
```



```{r}
#data$infection_rate <-label_percent()(data$infection_rate) 
#data$infection_rate <- as.numeric(data$infection_rate)

```

```{r}
data$infection_rate <- format(data$infection_rate, scientific = FALSE)
data$death_rate <- format(data$death_rate, scientific = FALSE)
data$vaccines_offered <- format(data$vaccines_offered, scientific = FALSE)
```

```{r}
data$infection_rate<-as.numeric(data$infection_rate)
data$death_rate<-as.numeric(data$death_rate)
data$vaccines_offered<-as.numeric(data$vaccines_offered)
```

```{r}
ui <- fluidPage(

   titlePanel("Covid-19 country level information"),
   
   sidebarLayout(
      sidebarPanel(
         selectInput("country",
                     "Select country:",
                     choices = country$location,
                     selected = "United States")
         
      ),
      
      mainPanel(
         plotlyOutput("infection"),
         plotlyOutput("death"),
         plotlyOutput("vaccine")
      )
   )
)


server <- function(input, output) {
   d <- reactive({input$country})
   l <- reactive({subset(data,location==d())})
   
   output$infection <- renderPlotly({
      g<-ggplot(l(),aes(x=date,y=infection_rate,text=paste("Country:",location,"\nDate: ",date,"\nInfection rate: ",infection_rate)))+
         geom_line(aes(group = 1),color = "#00AFBB", size = 1)+
         ggtitle("Total Infection Rate")+
         labs(x="Date (2022)",y="infection rate")+
         scale_x_date(date_labels = "%b %d",date_breaks = "4 weeks")+
         scale_y_continuous(labels = scales::percent_format(accuracy = 0.01))+
         theme_minimal()+
         theme(axis.text.x=element_text(angle=45, hjust=1))
     
      fig1<-ggplotly(g,tooltip = "text")
      fig1
                   
   })
   
   output$death <-renderPlotly({
      p<-ggplot(l(),aes(x=date,y=death_rate,text=paste("Country:",location,"\nDate: ",date,"\nDeath rate: ",death_rate)))+
         geom_line(aes(group = 1),color = "#E7B800", size = 1)+
         ggtitle("Total Death Rate")+
         labs(x="Date (2022)",y="Death rate")+
         scale_x_date(date_labels = "%b %d",date_breaks = "4 weeks")+
         scale_y_continuous(labels = scales::percent_format(accuracy = 0.001))+
         theme_minimal()+
         theme(axis.text.x=element_text(angle=45, hjust=1)) 
      options(scipen = 999)
      
      fig2<-ggplotly(p,tooltip="text")
      fig2
                   
   })

   output$vaccine <-renderPlotly({
      v<-ggplot(l(),aes(x=date,y=vaccines_offered,text=paste(
         "Country:",location,"\nDate: ",date,"\nTotal Vaccinations offered: ",vaccines_offered)))+
         geom_line(aes(group = 1),color = "#FC4E07", size = 1)+
         ggtitle("Total Vaccination offered")+
         labs(x="Date (2022)",y="Total Vaccination offered")+
         scale_x_date(date_labels = "%b %d",date_breaks = "4 weeks")+
         scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))+
         theme_minimal()+
         theme(axis.text.x=element_text(angle=45, hjust=1)) 
      fig3<-ggplotly(v,tooltip="text")
      fig3
                   
   })
}

shinyApp(ui = ui, server = server)
```

