library(shiny)
library(shinythemes)
library(ggplot2)
library(tidyverse)
library(readr)
library(ggthemes)
library(plotly)
library(shinydashboard)
library(dashboardthemes)
library(bslib)
library(showtext)

graph3_data <- read_csv('www/data/graph3.csv')
graph4_data <- read_csv('www/data/graph4.csv')
graph4_country <- read_csv('www/data/graph4_country.csv')

font_add(family = "	TimesModern-Bold", regular = "www/font/TimesModernBold.woff2.ttf")
font_add(family = "	Cardo-Regular", regular = "www/font/Cardo-Regular.ttf")
