---
title: "group_project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Question: Worldwide-level:How does vaccination doses relate to country variations in health care infrastructure, say, it is expected that countries with higher GDP per capita will have more people getting vaccinated (in per 100K people). We would also look at indicators like region and mortality rate.
```

```{r}

library("dplyr")
library("plotly")
# read the data file
df = read.csv('owid-covid-data.csv')

df <- df %>%
  filter(!is.na(people_vaccinated), !is.na(people_fully_vaccinated), !is.na(continent), !is.na(gdp_per_capita))

# gdp_per_capita, population, people_fully_vaccinated_per_hundred
df1 <- df %>%
  group_by(location) %>%
  summarise(gdp_per_capita = min(gdp_per_capita), population = max(population), people_fully_vaccinated_per_hundred = max(people_fully_vaccinated_per_hundred))

df2 <- df1 %>%
  arrange(desc(gdp_per_capita)) %>%
  head(20)
  
df2 %>%
  ggplot(aes(x = reorder(location, -gdp_per_capita), y = people_fully_vaccinated_per_hundred, fill = location)) +
    geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  ggtitle("Vaccination Rate of The Top 20 Countries with Highest GDP Per Capita") +
  xlab("Country") + ylab("People Fully Vaccinated Per Hundred") + 
  geom_hline(yintercept = mean(df2$people_fully_vaccinated_per_hundred), color="blue") +
  theme(legend.position = "none")

# This plot shows the vaccination rate of top 20 countries with highest GDP per capita. 
# The country(x axis) is ordered by gdp_per_capita from highest to lowest (Qatar has the highest GDP per capita)
# The blue line indicates the average vaccination rate of the 20 countries with highest GDP per capita.

# Takeaways:
# - From the chart,as GDP increases from left to right on x-axis, the vaccination rate (bar) does not increase correspondingly. Instead, it fluctuates when x value increases. This means that the variable 'GDP per capita' does not correlate with the vaccination rate.
# - The very salient point on the chart is the bar that represents 'Luxembourg'. It shows that although Luxembourg is ranked 3rd on GDP Per capita, it only has about 5 vaccination rate per hundred. This can further illustrate the above point that the variable 'GDP per capita' does not correlate with the vaccination rate.

```
```{r}

df_content = read.csv('owid-covid-data.csv')

df_content <- df_content %>%
  filter(!is.na(people_vaccinated), !is.na(people_fully_vaccinated), !is.na(gdp_per_capita))

df_content1 <- df_content %>%
  group_by(continent) %>%
  summarise(gdp_per_capita = mean(gdp_per_capita), people_fully_vaccinated_per_hundred = mean(people_fully_vaccinated_per_hundred)) %>%
  filter(continent != '')

df_content1 %>%
  ggplot(aes(x = reorder(continent, -gdp_per_capita), y = people_fully_vaccinated_per_hundred, fill = continent)) +
    geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  ggtitle("Vaccination Rate over 6 Continents") +
  xlab("Continent") + ylab("People Fully Vaccinated Per Hundred") + 
  geom_hline(yintercept = mean(df_content1$people_fully_vaccinated_per_hundred), color="blue") +
  theme(legend.position = "none")

# This plot shows the vaccination rate over 6 continents (How vaccination rate is distributed in different regions). 
# Takeaways:
# - Africa has the lowest percentage of receiving vaccinations. 
# - For other 5 continents, vaccination rates do not differ very much. 

```


